#! perl

use alienfile;
use Path::Tiny;

share {

    plugin Download => (
        url     => 'https://github.com/ericmandel/xpa/archive/v2.1.18.tar.gz'
    );

    plugin Extract           => 'tar.gz';

    patch [ '%{patch} -p1 < %{.install.patch}/v2.1.18.diffs' ];
    patch sub {
        my ( $build ) = @_;

        # Makefile.in uses INSTALL_ROOT instead of DESTDIR
        my $text = path( 'Makefile.in')->slurp;
        $DB::single=1;
        $text =~ s/^INSTALL_ROOT\s*=\s*$//m;
        $text =~ s/INSTALL_ROOT/DESTDIR/g;
        path( 'Makefile.in')->spew( $text);
        };

    plugin 'Build::Autoconf' => ();
};
