---
abstract: 'Find or Build libxpa'
author:
  - 'Diab Jerius <djerius@cpan.org>'
build_requires:
  Action::Retry: '0'
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  Capture::Tiny: '0'
  Child: '0'
  ExtUtils::MakeMaker: '7.50'
  File::Slurper: '0'
  File::Spec: '0'
  File::Which: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test2::Bundle::Extended: '0'
  Test2::V0: '0'
  Test::Alien: '0'
  Test::More: '0'
  perl: '5.006'
  subs: '0'
configure_requires:
  Alien::Build: '1.19'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-XPA
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Alien::XPA:
    file: lib/Alien/XPA.pm
    version: '0.11'
requires:
  Alien::Base: '0'
  base: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Alien-XPA
  repository: https://gitlab.com/djerius/alien-xpa.git
version: '0.11'
x_alienfile:
  generated_by: 'Dist::Zilla::Plugin::AlienBuild version 0.29'
  requires:
    share:
      Archive::Tar: '0'
      Config: '0'
      HTML::LinkExtor: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      IO::Zlib: '0'
      Net::SSLeay: '1.49'
      Sort::Versions: '0'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_generated_by_perl: v5.28.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: GPL-3.0-only
